//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditTask2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Article
    {
          
          
        public virtual Journalist Journalist { get; set; }

        public int articleId { get; set; }
        public Nullable<int> journId { get; set; }

        [DisplayName("Date of Issue")]

        [Controllers.ArticlesController.CheckDateRangeAttribute]
        public Nullable<System.DateTime> articleDate { get; set; }

        [Required(ErrorMessage = "Please enter a article topic")]
        [DisplayName("Topic")]
        [StringLength(50)]
        public string articleTopic { get; set; }
        [Required(ErrorMessage = "Please enter a Article Title")]
        [DisplayName("Title")]
        [StringLength(50)]
        public string articleTitle { get; set; }
        [DisplayName("Description")]

        public string articleDesc { get; set; }

    }
}
