//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CreditTask2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;


    public partial class Journalist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]

        public Journalist()
        {
            this.Articles = new HashSet<Article>();
        }

        public int journId { get; set; }
        [Required(ErrorMessage = "Please enter a first name")]
        [DisplayName("First Name")]
        [StringLength(50)]
        public string journFname { get; set; }
        [DisplayName("Last Name")]
        [Required(ErrorMessage = "Please enter a last name")]
        [StringLength(50)]
        public string JournLname { get; set; }

        [DisplayName("Date of Birth")]

        [Controllers.JournalistsController.CheckDateRangeAttribute]

        public Nullable<System.DateTime> journDOB { get; set; }

        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"[0-9]{10}", ErrorMessage = "Enter a Valid 10-digit phone number")]
        [DisplayName("Contact No.")]
        public Nullable<decimal> journContact { get; set; }
        [Required]
        [StringLength(80)]
        [EmailAddress(ErrorMessage = "Please enter a valid email address")]
        [DisplayName("Email Address")]
        public string journEmail { get; set; }
        [DisplayName("City")]
        public string journCity { get; set; }

        public string Journalist_Password { get; set; }
        public string Id_System { get; set; }
        [DisplayName("Picture")]
        public string Journalist_Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
    }

 
}
